### ISSUE TITLE
POST http://localhost:3000/api/message net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by marcothinnes** [sayurimizuguchi/conversation-with-discovery#1]
Hi,
Probably you can help me with that.

The bot runs as expected until I use an intent which should trigger the discovery long tail search.
 
So here is what I get in my terminal:
"next(error);
              ^

ReferenceError: next is not defined
..."

And then my server crashes.

Here is what's printed out in my browser console:
"POST http://localhost:3000/api/message net::ERR_EMPTY_RESPONSE"

Can you help me with that?

Thank you very much

**Comment by sayurimizuguchi** [comment]
Did you insert the Service Credentials from your Discovery service?

You need to debug what the error that the `next `are getting. So, try to use `console.log(error)` instead `next(error)` and saw the error that you are receiving when you're using the trigger for Discovery.
