### ISSUE TITLE
Discovery is not working

### ISSUE THREAD

**Issue by AlaGarali** [sayurimizuguchi/conversation-with-discovery#2]
Dear Sir @sayurimizuguchi ,
I'm creating my first chatbot application. Conversation service is working but Discovery service is not working knowing that I have added discovery intent and questions and in dialog I have discovery dialog node. 
![image](https://user-images.githubusercontent.com/30980622/42638396-70392f86-85e5-11e8-95be-095f4c6abf92.png)

- The extensions of documents uploaded in discovery service are .html, .docx, .json and .pdf.

- The response.result[0].text variable returned is the entire text and not the first text.

- Parameters of the params variable, maybe, are not functional:
 var params = {query: query, // only querying the text field
        //natural_language_query: query
        //filter: score>0.8,
        highlight: true,
        passages_count: 1,
        passages: true,
        return_fields: ['text'],
        count:1,
        return: 'text'
    }

Please find attached th source code of my chatbot application.
[my_chatbot.zip](https://github.com/sayurimizuguchi/conversation-with-discovery/files/2188917/my_chatbot.zip)

Let us suppose that the errors are fixed, how can we have the right answer to the question asked, from discovery service ? How can we configure params or discovery to return the best answer of user's question ?

Please help me to find the solution.

**Comment by sayurimizuguchi** [comment]
Dear @AlaGarali,
Apologize for my delay, too busy nowadays.

If you set all environment variables, Watson Discovery will work, **note** that I use one `context variable` to get the respective action that you want, So, you should add the context variable on the correct part of the conversation (node within Watson Conversation).

About your question: You should read the entire API documentation to get what each parameter do first, [check this out.](https://www.ibm.com/watson/developercloud/discovery/api/v1/node.html?node#query)

I would suggest you use `natural_language_query` parameter. You cannot use query and natural_language_query at the same time.

Any help, I'll answer asap.
