### ISSUE TITLE
Calling Discovery issue

### ISSUE THREAD

**Issue by mjpradeep** [sayurimizuguchi/conversation-with-discovery#3]
hi ,

I am able to run the code locally and connected my own conversation and discovery services with the app but when i am calling discovery service its responding back with the query results but i want to know get the pdf link and when we click it should open the pdf in different window. 
Same like below link,
https://assistant-with-discovery.ng.bluemix.net/

Please let me know how to get the results like above format.
I have removed the discovery results comments from app.js but its giving me the full document data but not the link.

//if you want to send all text returned from discovery, discomment these lines
               var text;
                  for (var i = 0; i < returnDiscovery.results.length; i++) {
                    text += returnDiscovery.results[i].text + "<br>";
                  }
              //sending the TEXT returned from discovery results
              response.output.text = 'Discovery call with success, check the results: <br>' + text;

**Comment by sayurimizuguchi** [comment]
Hi @mjpradeep, in this case you need to add `custom code` to do that.
_My sample example is how to integrate the two services and answer with the response from Discovery_.  
Customizations like you are talking about, needs custom code, like adding another library to save the return from discovery in one PDF, save in one server and send a link to the user. You can Ask question like that on [StackOverflow](https://stackoverflow.com/).
You already have one example of how to add an action using Watson Assistant with Discovery. So, after you custom code added, you'll need to _send the link to the user in your chat_, so you need to send one hyperlink with the PDF file from the server, here one of [how to send hyperlinks with Watson Assistant](https://stackoverflow.com/questions/43622965/ibm-watson-how-do-i-add-a-hyperlink-to-watson-responses/43641653#43641653).

**Comment by sayurimizuguchi** [comment]
This ISSUE is not a problem with **calling discovery.**

**Comment by mjpradeep** [comment]
@sayurimizuguchi, thanks for the replay,
I was able to get the results from discovery service last week but when i try to run the same code its giving me undefined message in chatbot..
Server running on port: 3000
Calling discovery..
return from discovery: [object Object]

**Comment by mjpradeep** [comment]
I am still getting the same error .. could  you please advise what issue.
I was able to get the results from discovery service last week but when i try to run the same code its giving me undefined message in chatbot..
Server running on port: 3000
Calling discovery..
return from discovery: [object Object]

**Comment by sayurimizuguchi** [comment]
This seems to be a code issue, my advice is to you post your error and your code at StackOverflow.
