### ISSUE TITLE
i can't understand what returnDiscovery do?

### ISSUE THREAD

**Issue by MahmoudBustami** [sayurimizuguchi/conversation-with-discovery#4]
please i used the `updateMessage`  function in my code but i do not understand  what `returnDiscovery` do
i get this error
![ret](https://user-images.githubusercontent.com/42839072/63727468-ac9e9380-c860-11e9-8743-fcba98fb3e54.JPG)

and this is the function
function updateMessage(res, input, response) {
     if (!response.output) {
         response.output = {};
     } else 
     //console.log(JSON.stringify(response.output));
     console.log(response.output.generic[0].text);
     if (response.output.generic[0].text === "calling Discovery") {
      
        console.log('Calling discovery from code');
        discovery.query(params, (returnDiscovery) => {
              console.log('return from discovery: '+returnDiscovery);
              //if you want to send all text returned from discovery, discomment these lines
                var text;
                  for (var i = 0; i < returnDiscovery.results.length; i++) {
                    text += returnDiscovery.results[i].text + "<br>";
                  }
              //sending the TEXT returned from discovery results
              response.output.text = 'Discovery call with success, check the results: <br>' + text; //results */
              //sending the PASSAGES returned from discovery results
              response.output.text = 'Discovery call with success, check the results: <br>' + returnDiscovery.passages[0].passage_text; //passageResults
              return res.json(response);
            
        });
    } else if (response.output && response.output.text) {
        return res.json(response);
    }
}

thank you

**Comment by MahmoudBustami** [comment]
`next `is undefined

**Comment by sayurimizuguchi** [comment]
You must set your credentials for Watson Discovery to be able to verify the `returnDiscovery` results.
Follow the steps in the READ.ME one by one and you won't have issues.
